### ISSUE TITLE
Can't add extensions to FireFox

### ISSUE THREAD

**Issue by pheyvaer** [KNowledgeOnWebScale/solid-authentication-browser-extension#4]
I can't add the extension to FireFox Developer Edition 109.0b6 (64-bit). I get the message that the extension is corrupt.

**Comment by axellorreyne** [comment]
The content script(s) are called from the "main" javascript file that is called from the popup browser action interface, therefore I initially didn't add a 'content_script' section in the manifest.json. Because the url matching section ("matches") is required, importing the artifact as a temporary extension in the firefox development built returns an error.

I added a content_scripts section to the manifest, not calling any scripts and matching any url

**Comment by axellorreyne** [comment]
Tested in Firefox Developer Edition 110.0b3 (64-bits)
